### ISSUE TITLE
pool

### ISSUE THREAD

**Issue by wiico** [RavenCommunity/kawpow-stratum-pool#1]
Hi

thank for this job.

wich frontend does work with it ?

**Comment by wiico** [comment]
ok i build with NOMP and change stratum-pool by your

stratum is up with test net and value seem good 

2020-05-04 10:42:23 [Pool]      [raven] (Thread 1) Stratum Pool Server Started for raven [RVN] {kawpow}
                                                Network Connected:      Testnet
                                                Detected Reward Type:   POW
                                                Current Block Height:   287185
                                                Current Block Diff:     21.076894554
                                                Current Connect Peers:  12
                                                Network Hash Rate:      1.31 GH
                                                Stratum Port(s):        3008, 3032, 3256
                                                Block polling every:    1000 ms
2020-05-04 10:42:23 [Switching] [Setup] (kawpow) Setting proxy difficulties after pool start


but when i start miner ( last miner with kawpow ) stratum crash

handleMessage (<<<): {"id":1,"jsonrpc":"2.0","method":"mining.subscribe","params":[]}
sendJson (>>>): {"id":1,"result":[null,"97ad5e"],"error":null}

sendJson (>>>): {"id":null,"method":"mining.set_target","params":["0000000007f80000000000000000000000000000000000000000000000000000"]}

sendJson (>>>): {"id":null,"method":"mining.notify","params":["000000000000000000000000000000000000000000000000000000000000cccd","f883ba9bc2bb28cdf1bfdc36b99af91c2558ddf32762edb4ab9ef84c3124970b","5197b2a3898b31d4d8afb33e2216b2ef6e166b09122e514323701e9af3b09643","0000000007f80000000000000000000000000000000000000000000000000000",true,287187,"1c0c1310"]}

handleMessage (<<<): {"id":3,"jsonrpc":"2.0","method":"mining.authorize","params":["mhQfjS4S37knQsz4B1jJrMGRxU5Bet3sT8","x"]}
2020-05-04 10:47:52 [Pool]      [raven] (Thread 1) Authorized mhQfjS4S37knQsz4B1jJrMGRxU5Bet3sT8.noname:x [::ffff:82.64.135.16]
/home/wiico/p/raven/libs/poolWorker.js:169
                callback({
                ^

TypeError: callback is not a function
    at /home/wiico/p/raven/libs/poolWorker.js:169:17
    at Object.handlers.auth (/home/wiico/p/raven/libs/poolWorker.js:135:21)
    at Object.authorizeFN [as authorizeFn] (/home/wiico/p/raven/libs/poolWorker.js:164:22)
    at handleAuthorize (/home/wiico/p/raven/node_modules/stratum-pool/lib/stratum.js:141:17)
    at handleMessage (/home/wiico/p/raven/node_modules/stratum-pool/lib/stratum.js:68:17)
    at /home/wiico/p/raven/node_modules/stratum-pool/lib/stratum.js:255:25
    at Array.forEach (<anonymous>)
    at Socket.<anonymous> (/home/wiico/p/raven/node_modules/stratum-pool/lib/stratum.js:240:26)
    at emitOne (events.js:116:13)
    at Socket.emit (events.js:211:7)
2020-05-04 10:47:52 [Master]    [PoolSpawner] Fork 0 died, spawning replacement worker...

**Comment by wiico** [comment]
do you think it's a node version issue ?

**Comment by LucasNoga** [comment]
Hello,
You should log the parameters of the instruction below to see which parameters are invalid 

stratum.js line 141 
options.authorizeFn(_this.remoteAddress, options.socket.localPort, _this.workerName, _this.workerPass, _this.extraNonce1, _this.version, function(result) {
            _this.authorized = (!result.error && result.authorized);

**Comment by mcsnoogins** [comment]
Which front end did you use? Does this still work?

**Comment by blackmennewstyle** [comment]
@wiico Can you provide a simple tutorial on how to integrate this stratum in NOMP?
